// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

using StardekkMediorFullstackDeveloper.DAL;

using System;

namespace StardekkMediorFullstackDeveloper.Migrations
{
    [DbContext(typeof(StardekkDatabaseContext))]
    partial class StardekkDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("StardekkMediorFullstackDeveloper.Models.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("StardekkMediorFullstackDeveloper.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoomTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("StardekkMediorFullstackDeveloper.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaximumOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumOccupancy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");
                });

            modelBuilder.Entity("StardekkMediorFullstackDeveloper.Models.Amenity", b =>
                {
                    b.HasOne("StardekkMediorFullstackDeveloper.Models.RoomType", null)
                        .WithMany("Amenities")
                        .HasForeignKey("RoomTypeId");
                });

            modelBuilder.Entity("StardekkMediorFullstackDeveloper.Models.Room", b =>
                {
                    b.HasOne("StardekkMediorFullstackDeveloper.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("StardekkMediorFullstackDeveloper.Models.RoomType", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
